### ISSUE TITLE
Decorator and =

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/pyDive#12]
@RemiLehe and I were testing the default example for [map](https://computationalradiationphysics.github.io/pyDive/modules.html#module-pyDive.algorithm) and realized it does not work with replacing the `*=` or `+=` with a `=`:

``` python
import pyDive

cluster_array = pyDive.ones(shape=[100], distaxis=0)

# works
cluster_array *= 2.0

# works
@pyDive.map
def twice(a):
    a *= 2.0

# does not work
@pyDive.map
def twiceAgain(a):
    a = a * 2.0

twice(cluster_array)      # works
twiceAgain(cluster_array) # does not change the values
```

is that a bug?

version used: current stable version from `pip`.

**Comment by heikoburau** [comment]
This is not a bug it is due to python's interpretation of `=`. The line `a = a * 2.0` means that `a` shall be remapped to the (temporary) result of `a * 2.0`. So after that `a` is no longer pointing to `cluster_array`.
`a[:] = a * 2.0` would be correct in this case.

**Comment by ax3l** [comment]
ah all right, that makes perfectly sense!
thank you!
