### ISSUE TITLE
Non-Element-Wise Operations for each Block

### ISSUE THREAD

**Issue by RemiLehe** [ComputationalRadiationPhysics/pyDive#13]
In the standard `pyDive.map` as explained by the documentation, each decorated function is applied to the local block element-wise (is that correct ?). It would however be much faster to apply the function directly to the local block as a numpy array (assuming that the function can be appplied to a numpy array) as it is much faster. Consider for instance the following 

``` python
import numpy as np

def f(x) :
    # Square function ; can be applied to a scalar or a numpy array
    return(x**2)

array_on_one_proc = np.random.rand(4000)

# Applying the function on a numpy array 
array_square = f(array_on_one_proc)  
# Output from %timeit : 100000 loops, best of 3: 3.62 µs per loop

# Applying the function element-wise (500 times slower)
array_square = map( f, array_on_one_proc )
# Output from %timeit : 100 loops, best of 3: 1.98 ms per loop
```

Which one of the two implementation is pyDive applying under the hood ?

**Comment by heikoburau** [comment]
The decocated functions is applied on a whole local block, i.e. not element-wise.

**Comment by RemiLehe** [comment]
Thanks. That's very clear.
