### ISSUE TITLE
Add Maintainer Documentation

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/pyDive#2]
Add Maintainer Documentation: Probably the wiki is a good place for that.

Instructions for the following questions:
- [x] _How to update the pip repositories?_ (add scripts?)
- [x] _How to update the Sphinx documentation on `gh-pages`?_ (add a nice [update.sh script](https://github.com/ComputationalRadiationPhysics/libSplash/blob/gh-pages/update.sh) as we did in `libSplash`)
- [x] Are tests used so far? _How to extend the python tests?_
- [x] release workflow (missing so far: version numbers (and version.hpp), tags, zenodo/doi/ ...)

**Comment by heikoburau** [comment]
The py.test framework is used in pyDive. Tests can be run by python setup.py test. All tests are located in pyDive/test

**Comment by ax3l** [comment]
cool, can you pls just link the information required to extend/update that in a (to be created) maintainer documentation? :+1: 

Aka a section _How to extend the python tests?_ (two sentences and a link might be enough for that)

**Comment by heikoburau** [comment]
I've just added a wiki

**Comment by ax3l** [comment]
fantastico! :sparkles: 

side question: did you create the images yourself (pls take care with their copyright)?

**Comment by heikoburau** [comment]
openclipart :)

**Comment by ax3l** [comment]
ok, so it's **CC0 1.0**. Well done! :)

(with CC-BY one has to set at least a reference in the footer/image caption to the author)

**Comment by ax3l** [comment]
@Heikman can you pls still push your release tag(s) via:

``` bash
git push mainline --tags
```

I personally always create them online on the GitHub homepage, that makes that a bit easier.
